### PR TITLE
New blahs

### PR DESCRIPTION
**Pull request by Haroenv**
Just as described in #2 

For the moment I'm still doing something wrong with the tests (decode doesn't work although it works when I try it externally)

And I've accidentally bumped the version too much (so the git tag and two useless commits will need to be removed)

### CODE REVIEW

**Comment by Haroenv** [comment]
Note: I managed to fix my tag mess, so @mischah still needs to bump because I can't <3

And fix the tests

**Comment by Haroenv** [comment]
Lookie there, I found out what was wrong with the tests: I didn't notice the first encode was different from the first decode. 

AFAIK :shipit:

**Comment by Haroenv** [comment]
Can be squashed if you prefer that

**Comment by mischah** [comment]
Thanks. Going to have a look at it as soon as the kiddo felt asleep :sleeping:

**Comment by Haroenv** [comment]
AFAIK, it should be merge, and then you can push it to npm, update the version in the cli and in the demo

**Comment by mischah** [comment]
Yeah. Please squash that :+1:

**Comment by Haroenv** [comment]
squashed, now lets wait on our buddy travis @mischah

**Comment by radiovisual** [comment]
:+1:

**Comment by mischah** [comment]
I refactored the ape language to make use of new stuff.

**Comment by Haroenv** [comment]
@mischah, you are cool!

**Pull request merged**
