### PR TITLE
Added ape-code. Reasons:

### PR DESCRIPTION
**Pull request by hardcoded-dev**
- A code should be writable and readable by orang-utans.
- To this end, the code should be simple, easy to remember, and not mention the word "monkey".
- Bananas are good.

### CODE REVIEW

**Comment by Haroenv** [comment]
Looks like this wouldn't break the coding/decoding of regular `blah`s to me @mischah

**Comment by mischah** [comment]
haha :joy: 

This is an awesome addition :monkey_face: 

Would you like to this as a secret feature? Otherwise you could update the readme as well. 

I think I would prefer this as a secret feature (easter egg) . Because it has nothing to to with `blah`.
Maybe there is more input from other @bullgit/gitches …

> Looks like this wouldn't break the coding/decoding of regular blahs to me @mischah

Yeah. Test are green :white_check_mark: 

@hardcoded-dev You could also add a few simple tests in the style of:
https://github.com/bullgit/blah-code/blob/master/test.js if you like to. Otherwise we won’t recognize if future changes will break your methods.

**Comment by hardcoded-dev** [comment]
I've already added similar testcases. The diff hides the changes of test.js below.

**Comment by mischah** [comment]
Oops. I missed that :blush:

**Comment by hardcoded-dev** [comment]
It's ok to have this as secret feature.

**Comment by mischah** [comment]
Going to prepare a release tonight :shipit:

**Comment by mischah** [comment]
Released `v1.3.0`

https://github.com/bullgit/blah-code/releases/tag/1.3.0

**Pull request merged**
