### PR TITLE
make instant

### LINKED ISSUE #7: Live updating
I'll quote @ArnaudWeyts

> Waarom is da niet live-updating zo da je niet op de knop moet drukken?

translation

> Why isn't this live-updating (i.e. convert on `input.addEventListener('input')` instead of `buttonaddEventListener('click')`?

### PR DESCRIPTION
**Pull request by Haroenv**
changed to eventlistener on #input
no more button
changed some querySelector's to getElementById

Fixes #7

### CODE REVIEW

**Comment by mischah** [comment]
Awesome.

But I think we should also trigger converting when:
- changing the language
- change mode (decode/encode)

What do you think?

**Comment by Haroenv** [comment]
Ah yeah good idea

I wouldn't make it run when you change the mode, because you might wanna copy the text you just translated and then decrypt it, so if it'd run then you'd get nothing and lose your original string

the language changed is a good idea though

**Comment by Haroenv** [comment]
I've updated it a bit now @mischah

**Comment by mischah** [comment]
:shipit:

**Pull request merged**
